(def throw_error (fn throw_error () 
  (throw "Error")
))

(throw_error)